  include "../constants.asm"
  org #0000
phantomas2_game_song2:
  db 7,184
phantomas2_game_song2_loop:
  db MUSIC_CMD_REPEAT, 2
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 30
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 25
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 14
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_END_REPEAT
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 45
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 44
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 25
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 41
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 14
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 38
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 45
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 44
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 25
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 41
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 14
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 14
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 44
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 25
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 45
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 41
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 14
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 38
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 44
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 25
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 45
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 41
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 14
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 26
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_REPEAT, 2
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 49
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 50
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 25
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 49
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 25
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 48
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 21
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 24
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 24
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 24
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 24
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_END_REPEAT
  db MUSIC_CMD_GOTO
  dw (phantomas2_game_song2_loop - phantomas2_game_song2)
